# Generated by Django 2.1.5 on 2019-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
