# Generated by Django 2.1.5 on 2019-06-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='contenido',
            new_name='comentario',
        ),
    ]
