# Generated by Django 2.1.5 on 2019-06-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_auto_20190623_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='image',
            field=models.ImageField(null=True, upload_to='img/galeria'),
        ),
    ]
