# Generated by Django 2.1.5 on 2019-06-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_galeria_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/about-me')),
                ('pregunta', models.CharField(max_length=1000)),
                ('respuesta', models.TextField(help_text='respuesta de la pregunta')),
            ],
        ),
        migrations.AlterField(
            model_name='galeria',
            name='comentario',
            field=models.TextField(help_text='comentario de la foto', null=True),
        ),
    ]
