# Generated by Django 2.1.5 on 2019-06-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_proyecto_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='caracteristica',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristica', to='contenido.Proyecto'),
        ),
    ]
