# Generated by Django 2.1.5 on 2019-02-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.ImageField(upload_to='img')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'RedSocial',
                'verbose_name_plural': 'RedSocials',
            },
        ),
        migrations.AddField(
            model_name='fodder',
            name='red_social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.RedSocial'),
            preserve_default=False,
        ),
    ]
